name: audio_service
description: Flutter plugin to play audio in the background while the screen is off.
version: 0.8.0
homepage: https://github.com/ryanheise/audio_service

environment:
  sdk: '>=2.6.0 <3.0.0'
  flutter: ">=1.12.8 <2.0.0"

dependencies:
  rxdart: ^0.24.0
  flutter_isolate: ^1.0.0+12
  flutter_cache_manager: ^1.2.2
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ryanheise.audioservice
        pluginClass: AudioServicePlugin
      ios:
        pluginClass: AudioServicePlugin
